/*
 * ClothFRM.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Color;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pojo.Cloth;
import pojo.User;
import dao.ClothDAO;
import dao.UserDAO;

/**
 *
 * @author  __朱建强__
 */
public class ClothFRM extends javax.swing.JFrame {

	/** Creates new form ClothFRM */
	public ClothFRM() {
		initComponents();
		this.setLocationRelativeTo(null);
		this.setBackground(Color.blue);
		DefaultTableModel model = (DefaultTableModel) this.clothTable
				.getModel();
		ClothDAO clothDao = new ClothDAO();
		List<Cloth> list = clothDao.searchClothes();
		for (int i = 0; i < list.size(); i++) {
			Vector v = new Vector();
			v.add(list.get(i).getClothid());
			v.add(list.get(i).getClothsort());
			v.add(list.get(i).getClothbrand());
			v.add(list.get(i).getClothstyle());
			v.add(list.get(i).getClothprice());
			model.addRow(v);
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		clothTable = new javax.swing.JTable();
		seoClothsort = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jTextField6 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 2, 36));
		jLabel1.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\Drinker\\MyEclipse-workspace\\java1\\src\\ima\\服装.png")); // NOI18N
		jLabel1.setText("\u670d\u88c5\u7ba1\u7406\u754c\u9762");

		clothTable.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null } },
				new String[] { "序列号", "类别", "品牌", "风格", "价格" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					true };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		clothTable.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				clothTableMousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(clothTable);


		jButton1.setText("\u641c\u7d22");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel2.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\Drinker\\MyEclipse-workspace\\java1\\src\\ima\\搜索.png")); // NOI18N
		jLabel2.setText("\u8bf7\u8f93\u5165\u5173\u952e\u5b57\uff1a");

		jButton2.setText("\u4ece\u8863\u6a71\u4e2d\u53bb\u9664");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel3.setText("\u9009\u4e2d\uff1a");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(147,
																		147,
																		147)
																.addComponent(
																		jLabel2)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		seoClothsort,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		175,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(51, 51,
																		51)
																.addComponent(
																		jButton1))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(278,
																		278,
																		278)
																.addComponent(
																		jButton2))
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
																.addGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		layout.createSequentialGroup()
																				.addContainerGap()
																				.addComponent(
																						jLabel3)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jTextField2)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jTextField3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						110,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jTextField4,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						107,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jTextField5,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						104,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jTextField6,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						109,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																.addGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		layout.createSequentialGroup()
																				.addGap(66,
																						66,
																						66)
																				.addComponent(
																						jScrollPane1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						575,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(202,
																		202,
																		202)
																.addComponent(
																		jLabel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		287,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(76, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														seoClothsort,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jButton1))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										242,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(39, 39, 39)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														jTextField6,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jTextField2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jTextField3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jTextField4,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jTextField5,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										34, Short.MAX_VALUE)
								.addComponent(jButton2).addGap(34, 34, 34)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void clothTableMousePressed(java.awt.event.MouseEvent evt) {
		int row = this.clothTable.getSelectedRow();
		this.jTextField2.setText(this.clothTable.getValueAt(row, 0).toString());
		this.jTextField3.setText(this.clothTable.getValueAt(row, 1).toString());
		this.jTextField4.setText(this.clothTable.getValueAt(row, 2).toString());
		this.jTextField5.setText(this.clothTable.getValueAt(row, 3).toString());
		this.jTextField6.setText(this.clothTable.getValueAt(row, 4).toString());
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		String clothid = this.jTextField2.getText();
		String clothsort = this.seoClothsort.getText();
		if ("".equals(clothid) || clothid.length() == 0) {
			JOptionPane.showMessageDialog(null, "请你选择一行数据");
			return;
		} else {
			int result = JOptionPane.showConfirmDialog(null, "你确定删除吗");
			if (result == 0) {
				ClothDAO clothDao = new ClothDAO();
				int count = clothDao.deleteCloth(Integer.parseInt(clothid));
				if (count > 0) {
					JOptionPane.showMessageDialog(null, "已经从衣橱中去除");
					DefaultTableModel model = (DefaultTableModel) this.clothTable
							.getModel();
					model.setRowCount(0);
					List<Cloth> list = clothDao.searchClothesLike(clothsort);
					for (int i = 0; i < list.size(); i++) {
						Vector v = new Vector();
						v.add(list.get(i).getClothid());
						v.add(list.get(i).getClothsort());
						v.add(list.get(i).getClothbrand());
						v.add(list.get(i).getClothstyle());
						v.add(list.get(i).getClothprice());
						model.addRow(v);
					}
				} else {
					JOptionPane.showMessageDialog(null, "未能从衣橱中去除");
				}
			}
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String clothsort = this.seoClothsort.getText();
		DefaultTableModel model = (DefaultTableModel) this.clothTable
				.getModel();
		model.setRowCount(0);
		ClothDAO clothDao = new ClothDAO();
		List<Cloth> list = clothDao.searchClothesLike(clothsort);
		for (int i = 0; i < list.size(); i++) {
			Vector v = new Vector();
			v.add(list.get(i).getClothid());
			v.add(list.get(i).getClothsort());
			v.add(list.get(i).getClothbrand());
			v.add(list.get(i).getClothstyle());
			v.add(list.get(i).getClothprice());
			model.addRow(v);
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ClothFRM().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTable clothTable;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField seoClothsort;
	// End of variables declaration//GEN-END:variables

}