/*
 * ClothAddFRM.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Color;
import java.util.UUID;
import javax.swing.JOptionPane;
import dao.ClothDAO;
import dao.UserDAO;

/**
 *
 * @author  __朱建强__
 */
public class ClothAddFRM extends javax.swing.JFrame {

	/** Creates new form ClothAddFRM */
	public ClothAddFRM() {
		initComponents();
		this.setLocationRelativeTo(null);
		this.setBackground(Color.blue);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		clothbrand = new javax.swing.JTextField();
		clothstyle = new javax.swing.JTextField();
		clothprice = new javax.swing.JTextField();
		add = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		clothsort = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 2, 36));
		jLabel1.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\Drinker\\MyEclipse-workspace\\java1\\src\\ima\\服装.png")); // NOI18N
		jLabel1.setText("\u670d\u88c5\u6dfb\u52a0\u754c\u9762");

		jLabel2.setText("\u54c1\u724c\uff1a");

		jLabel3.setText("\u98ce\u683c\uff1a");

		jLabel4.setText("\u4ef7\u683c\uff1a");

		add.setText("\u52a0\u5165\u8863\u6a71");
		add.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addActionPerformed(evt);
			}
		});

		jLabel5.setText("\u7c7b\u522b\uff1a");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(42, 42,
																		42)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jLabel4)
																				.addComponent(
																						jLabel3)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel5))
																.addGap(45, 45,
																		45)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																				.addComponent(
																						clothprice,
																						javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						clothstyle,
																						javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						clothbrand,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						217,
																						Short.MAX_VALUE)
																				.addComponent(
																						clothsort,
																						javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel1,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						302,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(215,
																		215,
																		215)
																.addComponent(
																		add)))
								.addContainerGap(99, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addGap(24, 24, 24)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel5)
												.addComponent(
														clothsort,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						clothbrand,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel2))
																.addGap(65, 65,
																		65))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						clothstyle,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel3))
																.addGap(18, 18,
																		18)))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														clothprice,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4))
								.addGap(51, 51, 51).addComponent(add)
								.addContainerGap(76, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void addActionPerformed(java.awt.event.ActionEvent evt) {
		String clothsort = this.clothsort.getText();
		String clothbrand = this.clothbrand.getText();
		String clothstyle = this.clothstyle.getText();
		String clothprice = this.clothprice.getText();
		ClothDAO clothDAO = new ClothDAO();
		int count = clothDAO.createCloth(clothsort, clothbrand,clothstyle, Double.parseDouble(clothprice));
		if (count == 1) {
			this.dispose();
			JOptionPane.showMessageDialog(null, "服装添加成功");
			new ClothAddFRM().setVisible(true);
		} else {
			JOptionPane.showMessageDialog(null, "服装添加失败");
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ClothAddFRM().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton add;
	private javax.swing.JTextField clothbrand;
	private javax.swing.JTextField clothprice;
	private javax.swing.JTextField clothsort;
	private javax.swing.JTextField clothstyle;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	// End of variables declaration//GEN-END:variables

}