/*
 * RegisterFRM.java
 *
 * Created on __DATE__, __TIME__
 */

package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import dao.UserDAO;

/**
 *
 * @author  __朱建强__
 */
public class RegisterFRM extends javax.swing.JFrame {

	/** Creates new form RegisterFRM */
	public RegisterFRM() {
		initComponents();
		this.setLocationRelativeTo(null);
		this.setBackground(Color.blue);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		uname = new javax.swing.JTextField();
		upwd = new javax.swing.JTextField();
		register = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		unum = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u6ce8\u518c\u7cfb\u7edf");
		setAlwaysOnTop(true);


		register.setText("\u6ce8\u518c");
		register.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				registerActionPerformed(evt);
			}
		});

		jLabel1.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\Drinker\\MyEclipse-workspace\\java1\\src\\ima\\账号.png")); // NOI18N
		jLabel1.setText("\u8d26\u53f7\uff1a");

		jLabel2.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\Drinker\\MyEclipse-workspace\\java1\\src\\ima\\钥匙.png")); // NOI18N
		jLabel2.setText("\u5bc6\u7801\uff1a");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 36));
		jLabel3.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\Drinker\\MyEclipse-workspace\\java1\\src\\ima\\用户.png")); // NOI18N
		jLabel3.setText("\u7cfb\u7edf\u6ce8\u518c\u754c\u9762");

		jLabel4.setIcon(new javax.swing.ImageIcon(
				"C:\\Users\\Drinker\\MyEclipse-workspace\\java1\\src\\ima\\电话.png")); // NOI18N
		jLabel4.setText("\u7535\u8bdd\uff1a");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(260,
																		260,
																		260)
																.addComponent(
																		jLabel3))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(247,
																		247,
																		247)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel4))
																.addGap(83, 83,
																		83)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						unum,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						241,
																						Short.MAX_VALUE)
																				.addComponent(
																						upwd,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						241,
																						Short.MAX_VALUE)
																				.addComponent(
																						uname,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						241,
																						Short.MAX_VALUE))))
								.addGap(212, 212, 212))
				.addGroup(
						layout.createSequentialGroup().addGap(376, 376, 376)
								.addComponent(register)
								.addContainerGap(425, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(16, 16, 16)
								.addComponent(jLabel3)
								.addGap(29, 29, 29)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														uname,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(29, 29, 29)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														upwd,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(33, 33, 33)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														unum,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4))
								.addGap(36, 36, 36).addComponent(register)
								.addGap(62, 62, 62)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void registerActionPerformed(java.awt.event.ActionEvent evt) {
		String uname = this.uname.getText();
		String upwd = this.upwd.getText();
		String unum = this.unum.getText();
		UserDAO userDAO = new UserDAO();
		int count = userDAO.createUser(uname, upwd, unum);
		if (count == 1) {
			this.dispose();
			JOptionPane.showMessageDialog(null, "用户注册成功");
			new LoginFRM().setVisible(true);
		} else {
			JOptionPane.showMessageDialog(null, "用户注册失败");
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RegisterFRM().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JButton register;
	private javax.swing.JTextField uname;
	private javax.swing.JTextField unum;
	private javax.swing.JTextField upwd;
	// End of variables declaration//GEN-END:variables

}